/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/portfolio.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portfolio Data
         * @description Returns the complete portfolio data including projects, writing samples, and about information.
         */
        get: operations["getPortfolio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Complete portfolio data structure */
        Portfolio: {
            /** @description List of portfolio projects */
            projects: components["schemas"]["Project"][];
            /** @description List of writing samples and essays */
            writing: components["schemas"]["Writing"][];
            about: components["schemas"]["About"];
        };
        /** @description A portfolio project */
        Project: {
            /**
             * @description The name of the project
             * @example YourCast
             */
            title: string;
            /**
             * @description Current development status of the project
             * @example Under Development
             * @enum {string}
             */
            status: "Under Development" | "Live" | "Completed";
            /**
             * @description Detailed description of the project
             * @example YourCast is a modern podcast discovery and AI-powered episode generation platform.
             */
            description: string;
            link: components["schemas"]["Link"];
        };
        /** @description A writing sample or essay */
        Writing: {
            /**
             * @description The title of the writing piece
             * @example Der grausame Gang der prunkvollen Nichtigkeit
             */
            title: string;
            /**
             * @description Publication date in DD.MM.YYYY format
             * @example 26.04.2025
             */
            date: string;
            /** @description Brief excerpt or description of the writing piece */
            description: string;
            link: components["schemas"]["Link"];
        };
        /** @description External link with metadata */
        Link: {
            /**
             * Format: uri
             * @description The URL to the external resource
             * @example https://github.com/neuromaxer/yourcast
             */
            url: string;
            /**
             * @description Display label for the link
             * @example Git-Hub
             */
            label: string;
            /**
             * @description Hex color code for styling (ARGB format)
             * @example 21FDFDFD
             */
            hex: string;
        };
        /** @description Personal information and contact details */
        About: {
            /**
             * @description Full name
             * @example Nicolas Py
             */
            name: string;
            /**
             * @description Professional title
             * @example Software Developer & Designer
             */
            title: string;
            /** @description Short biography */
            bio: string;
            /**
             * @description List of technical skills
             * @example [
             *       "Web Development",
             *       "AI/ML",
             *       "UI/UX Design",
             *       "Swift",
             *       "React",
             *       "TypeScript"
             *     ]
             */
            skills: string[];
            contact: components["schemas"]["Contact"];
        };
        /** @description Contact information */
        Contact: {
            /**
             * Format: email
             * @description Email address
             * @example contact@example.com
             */
            email: string;
            /**
             * Format: uri
             * @description GitHub profile URL
             * @example https://github.com/Nicolas-Py
             */
            github: string;
            /**
             * Format: uri
             * @description LinkedIn profile URL
             * @example https://linkedin.com/in/nicolas-py
             */
            linkedin: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful response with portfolio data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
}
